version: '3.8'

services:
  bot:
    build: .
    container_name: tg_media_downloader_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Agar cookies ishlatmoqchi bo'lsangiz, uni konteynerga bog'laymiz
      - ./cookies.txt:/app/cookies.txt:ro
    # Vaqtincha fayllarni saqlash uchun konteyner ichidagi /tmp ishlatiladi
